/* Auto-generated by tools/gen_font.py — do not edit manually */
#pragma once
#include "font_render.h"

/* LiberationSans-Regular.ttf  192px  U+0020–U+007E */
/* line_height=215  base_line=41 */
extern const font_t font_arial_192;
