/* Auto-generated by tools/gen_font.py — do not edit manually */
#pragma once
#include "font_render.h"

/* LiberationSans-Regular.ttf  128px  U+0020–U+007E */
/* line_height=144  base_line=28 */
extern const font_t font_arial_128;
