/* Auto-generated by tools/gen_font.py — do not edit manually */
#pragma once
#include "font_render.h"

/* LiberationSans-Regular.ttf  48px  U+0020–U+007E */
/* line_height=55  base_line=11 */
extern const font_t font_arial_48;
