#!/usr/bin/env python3
"""
gen_font.py — generate 4bpp font C/H source files for astrafw.

Usage:
    python3 tools/gen_font.py <path/to/Font.ttf> <size_px> [output_dir]

    size_px     Pixel size (e.g. 16, 20, 48, 192).
    output_dir  Where to write the .c/.h files.
                Defaults to main/font_render/.

Example:
    python3 tools/gen_font.py /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf 192

Requires:
    pip install freetype-py
"""

import sys
import os
import re
import math
import freetype

# Unicode range to include: U+0020 (space) … U+007E (~)
RANGE_START = 0x0020
RANGE_END   = 0x007E  # inclusive

BYTES_PER_LINE = 16   # hex bytes per row in the bitmap array


def render_glyph_4bpp(face, codepoint):
    """
    Render *codepoint* at the face's current pixel size.

    Returns (bitmap_4bpp: bytes, width: int, height: int, ofs_x: int, ofs_y: int, advance: int)
    where
        bitmap_4bpp  packed nibbles, MSN = left pixel
        width/height bounding box in pixels
        ofs_x        left bearing (px)
        ofs_y        top bearing above baseline (px, positive = above)
        advance      horizontal advance * 16  (fixed-point 12.4)
    """
    face.load_char(chr(codepoint),
                   freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    glyph   = face.glyph
    bitmap  = glyph.bitmap
    metrics = glyph.metrics

    width  = bitmap.width
    height = bitmap.rows
    ofs_x  = glyph.bitmap_left
    ofs_y  = glyph.bitmap_top   # positive = pixels above baseline

    # advance is in 26.6 fixed-point; convert to 12.4 by >> 2
    advance = (metrics.horiAdvance >> 2)   # units of 1/16 px

    if width == 0 or height == 0:
        return b'', 0, 0, 0, 0, advance

    # Freetype renders at 8bpp (0-255). Quantise to 4bpp [0-15].
    src = bytes(bitmap.buffer)
    nibbles = []
    for byte in src:
        nibbles.append((byte >> 4) & 0xF)   # 8→4 bit

    # Pack two nibbles per byte, MSN first; row pitch = ceil(width/2)
    packed = bytearray()
    for row in range(height):
        row_nibs = nibbles[row * width : row * width + width]
        for i in range(0, width, 2):
            hi = row_nibs[i]
            lo = row_nibs[i + 1] if (i + 1) < width else 0
            packed.append((hi << 4) | lo)

    return bytes(packed), width, height, ofs_x, ofs_y, advance


def generate(ttf_path, size_px, out_dir):
    face = freetype.Face(ttf_path)
    face.set_pixel_sizes(0, size_px)

    # Derive a clean name from the TTF filename, e.g. "arial" from
    # "LiberationSans-Regular.ttf"
    base = os.path.splitext(os.path.basename(ttf_path))[0]
    # Map known font names; fall back to a sanitised version of the filename.
    name_map = {
        "LiberationSans-Regular": "arial",
        "LiberationSans-Bold":    "arial_bold",
    }
    font_name = name_map.get(base, re.sub(r"[^a-z0-9]", "_", base.lower()))

    sym   = f"font_{font_name}_{size_px}"   # e.g. font_arial_192
    guard = sym.upper()                      # e.g. FONT_ARIAL_192

    # Collect font-level metrics (ascender / descender in pixels)
    metrics = face.size
    ascender  = math.ceil(metrics.ascender  / 64)   # px above baseline
    descender = abs(math.floor(metrics.descender / 64))  # px below (positive)
    line_height = ascender + descender

    # Render every glyph in the range
    glyphs = []   # list of (codepoint, packed_bytes, w, h, ox, oy, adv)
    for cp in range(RANGE_START, RANGE_END + 1):
        data, w, h, ox, oy, adv = render_glyph_4bpp(face, cp)
        glyphs.append((cp, data, w, h, ox, oy, adv))

    # Build the flat bitmap array and record offsets
    bitmap_blob = bytearray()
    offsets = []
    for (cp, data, w, h, ox, oy, adv) in glyphs:
        offsets.append(len(bitmap_blob))
        bitmap_blob.extend(data)

    total_bytes = len(bitmap_blob)

    # -----------------------------------------------------------------------
    # Write .c file
    # -----------------------------------------------------------------------
    c_path = os.path.join(out_dir, f"{sym}.c")
    with open(c_path, "w") as f:
        f.write(f"/* Auto-generated by tools/gen_font.py — do not edit manually */\n")
        f.write(f"/* Source: {os.path.basename(ttf_path)}  size: {size_px}px  range: U+{RANGE_START:04X}–U+{RANGE_END:04X} */\n")
        f.write(f"\n")
        f.write(f'#include "font_render.h"\n')
        f.write(f"\n")

        # Bitmap data
        f.write(f"/* {total_bytes} bytes of 4bpp glyph bitmap data */\n")
        f.write(f"static const uint8_t _{sym}_bitmap[] = {{\n")
        for i in range(0, total_bytes, BYTES_PER_LINE):
            chunk = bitmap_blob[i : i + BYTES_PER_LINE]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            eol = "," if (i + BYTES_PER_LINE) < total_bytes else ""
            f.write(f"    {hex_str}{eol}\n")
        f.write(f"}};\n\n")

        # Glyph descriptor table
        # notdef entry first (index 0, zero-size, same advance as space)
        space_adv = glyphs[0][6]  # advance of U+0020
        f.write(f"/* {1 + len(glyphs)} glyph descriptors (index 0 = notdef) */\n")
        f.write(f"static const font_glyph_dsc_t _{sym}_glyph_dsc[] = {{\n")
        f.write(f"    /* {{ bitmap_index, adv_w, box_w, box_h, ofs_x, ofs_y }} */\n")
        f.write(f"    {{      0,   {space_adv:3d},   0,   0,    0,    0 }},  /* notdef */\n")

        for idx, (cp, data, w, h, ox, oy, adv) in enumerate(glyphs):
            off  = offsets[idx]
            char = chr(cp)
            printable = char if char.isprintable() and char != '/' else '?'
            label = f"U+{cp:04X} '{printable}'"
            f.write(f"    {{ {off:6d},   {adv:3d},  {w:2d},  {h:2d},  {ox:4d},  {oy:4d} }},  /* {label} */\n")

        f.write(f"}};\n\n")

        # font_t instance
        range_len = RANGE_END - RANGE_START + 1
        f.write(f"const font_t {sym} = {{\n")
        f.write(f"    .glyph_bitmap  = _{sym}_bitmap,\n")
        f.write(f"    .glyph_dsc     = _{sym}_glyph_dsc,\n")
        f.write(f"    .range_start   = 0x{RANGE_START:04X}U,\n")
        f.write(f"    .range_length  = {range_len}U,\n")
        f.write(f"    .bpp           = 4,\n")
        f.write(f"    .line_height   = {line_height},\n")
        f.write(f"    .base_line     = {descender},\n")
        f.write(f"}};\n")

    # -----------------------------------------------------------------------
    # Write .h file
    # -----------------------------------------------------------------------
    h_path = os.path.join(out_dir, f"{sym}.h")
    with open(h_path, "w") as f:
        f.write(f"/* Auto-generated by tools/gen_font.py — do not edit manually */\n")
        f.write(f"#pragma once\n")
        f.write(f'#include "font_render.h"\n')
        f.write(f"\n")
        f.write(f"/* {os.path.basename(ttf_path)}  {size_px}px  U+{RANGE_START:04X}–U+{RANGE_END:04X} */\n")
        f.write(f"/* line_height={line_height}  base_line={descender} */\n")
        f.write(f"extern const font_t {sym};\n")

    print(f"Generated {c_path}  ({total_bytes} bitmap bytes)")
    print(f"Generated {h_path}")
    print(f"  line_height={line_height}  base_line={descender}  glyphs={len(glyphs)}")
    print()
    print("Remember to add the .c file to SRCS in main/CMakeLists.txt:")
    print(f'  "font_render/{sym}.c"')


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    ttf_path = sys.argv[1]
    size_px  = int(sys.argv[2])
    out_dir  = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
        os.path.dirname(__file__), "..", "main", "font_render"
    )

    if not os.path.isfile(ttf_path):
        print(f"Error: font file not found: {ttf_path}")
        sys.exit(1)

    os.makedirs(out_dir, exist_ok=True)
    generate(ttf_path, size_px, os.path.normpath(out_dir))


if __name__ == "__main__":
    main()
